use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, Enum, Serialize, Deserialize)]
pub enum MicrophoneType {
    XLR,
    Phantom,
    TRS,
}

/*
 As with everything else, we're going to keep the values to these keys isolated in the USB crate
 and have alternatives for direct access in goxlr-shared, where we don't have to care about
 changes
*/

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MicrophoneParamKeys {
    MicType,
    XLRGain,
    PhantomGain,
    TRSGain,
    GateThreshold,
    GateAttack,
    GateRelease,
    GateAttenuation,
    CompressorThreshold,
    CompressorRatio,
    CompressorAttack,
    CompressorRelease,
    CompressorMakeUpGain,
    BleepLevel,

    /*
     These are the values for the GoXLR mini, it seems there's a difference in how the two
     are setup, The Mini does EQ via mic parameters, where as the full does it via effects.
    */
    Equalizer90HzFrequency,
    Equalizer90HzGain,
    Equalizer250HzFrequency,
    Equalizer250HzGain,
    Equalizer500HzFrequency,
    Equalizer500HzGain,
    Equalizer1KHzFrequency,
    Equalizer1KHzGain,
    Equalizer3KHzFrequency,
    Equalizer3KHzGain,
    Equalizer8KHzFrequency,
    Equalizer8KHzGain,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MicrophoneEffectKey {
    MicInputMute,
    BleepLevel,
    GateMode,
    GateThreshold,
    GateEnabled,
    GateAttenuation,
    GateAttack,
    GateRelease,
    MicCompSelect,
    Equalizer31HzFrequency,
    Equalizer31HzGain,
    Equalizer63HzFrequency,
    Equalizer63HzGain,
    Equalizer125HzFrequency,
    Equalizer125HzGain,
    Equalizer250HzFrequency,
    Equalizer250HzGain,
    Equalizer500HzFrequency,
    Equalizer500HzGain,
    Equalizer1KHzFrequency,
    Equalizer1KHzGain,
    Equalizer2KHzFrequency,
    Equalizer2KHzGain,
    Equalizer4KHzFrequency,
    Equalizer4KHzGain,
    Equalizer8KHzFrequency,
    Equalizer8KHzGain,
    Equalizer16KHzFrequency,
    Equalizer16KHzGain,
    CompressorThreshold,
    CompressorRatio,
    CompressorAttack,
    CompressorRelease,
    CompressorMakeUpGain,
    DeEsser,
    ReverbAmount,
    ReverbDecay,
    ReverbEarlyLevel,
    ReverbTailLevel, // Always sent as 0.
    ReverbPredelay,
    ReverbLowColor,
    ReverbHighColor,
    ReverbHighFactor,
    ReverbDiffuse,
    ReverbModSpeed,
    ReverbModDepth,
    ReverbType,
    EchoAmount,
    EchoFeedback,
    EchoTempo,
    EchoDelayL,
    EchoDelayR,
    EchoFeedbackL,
    EchoFeedbackR,
    EchoXFBLtoR,
    EchoXFBRtoL,
    EchoSource,
    EchoDivL,
    EchoDivR,
    EchoFilterStyle,
    PitchAmount,
    PitchCharacter,
    PitchThreshold,
    GenderAmount,
    MegaphoneAmount,
    MegaphonePostGain,
    MegaphoneStyle,
    MegaphoneHP,
    MegaphoneLP,
    MegaphonePreGain,
    MegaphoneDistType,
    MegaphonePresenceGain,
    MegaphonePresenceFC,
    MegaphonePresenceBW,
    MegaphoneBeatboxEnable,
    MegaphoneFilterControl,
    MegaphoneFilter,
    MegaphoneDrivePotGainCompMid,
    MegaphoneDrivePotGainCompMax,
    RobotLowGain,
    RobotLowFreq,
    RobotLowWidth,
    RobotMidGain,
    RobotMidFreq,
    RobotMidWidth,
    RobotHiGain,
    RobotHiFreq,
    RobotHiWidth,
    RobotWaveform,
    RobotPulseWidth,
    RobotThreshold,
    RobotDryMix,
    RobotStyle,
    HardTuneKeySource, // Always sent as 0.
    HardTuneAmount,
    HardTuneRate,
    HardTuneWindow,
    HardTuneScale,
    HardTunePitchAmount,

    RobotEnabled,
    MegaphoneEnabled,
    HardTuneEnabled,

    Encoder1Enabled,
    Encoder2Enabled,
    Encoder3Enabled,
    Encoder4Enabled,
}
