/*
 As with everything else, we're going to keep the values to these keys isolated in the USB crate
 and have alternatives for direct access in goxlr-shared, where we don't have to care about
 changes
*/

type EffectKeys = goxlr_shared::microphone::MicEffectKeys;
type ParamKeys = goxlr_shared::microphone::MicParamKeys;

#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub(crate) enum DeviceMicParamKeys {
    MicType = 0x000,
    XLRGain = 0x001,
    PhantomGain = 0x002,
    JackGain = 0x003,
    GateThreshold = 0x30200,
    GateAttack = 0x30400,
    GateRelease = 0x30600,
    GateAttenuation = 0x30900,
    CompressorThreshold = 0x60200,
    CompressorRatio = 0x60300,
    CompressorAttack = 0x60400,
    CompressorRelease = 0x60600,
    CompressorMakeUpGain = 0x60700,
    BleepLevel = 0x70100,

    /*
     These are the values for the GoXLR mini, it seems there's a difference in how the two
     are setup, The Mini does EQ via microphone parameters, where as the full does it via effects.
    */
    Equalizer90HzFrequency = 0x40000,
    Equalizer90HzGain = 0x40001,
    Equalizer250HzFrequency = 0x40003,
    Equalizer250HzGain = 0x40004,
    Equalizer500HzFrequency = 0x40006,
    Equalizer500HzGain = 0x40007,
    Equalizer1KHzFrequency = 0x50000,
    Equalizer1KHzGain = 0x50001,
    Equalizer3KHzFrequency = 0x50003,
    Equalizer3KHzGain = 0x50004,
    Equalizer8KHzFrequency = 0x50006,
    Equalizer8KHzGain = 0x50007,
}

#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub(crate) enum DeviceMicEffectKeys {
    MicInputMute = 0x0158,
    BleepLevel = 0x0073,
    GateMode = 0x0010,
    GateThreshold = 0x0011,
    GateEnabled = 0x0014,
    GateAttenuation = 0x0015,
    GateAttack = 0x0016,
    GateRelease = 0x0017,
    MicCompSelect = 0x014b,
    Equalizer31HzFrequency = 0x0126,
    Equalizer31HzGain = 0x0127,
    Equalizer63HzFrequency = 0x00f8,
    Equalizer63HzGain = 0x00f9,
    Equalizer125HzFrequency = 0x0113,
    Equalizer125HzGain = 0x0114,
    Equalizer250HzFrequency = 0x0129,
    Equalizer250HzGain = 0x012a,
    Equalizer500HzFrequency = 0x0116,
    Equalizer500HzGain = 0x0117,
    Equalizer1KHzFrequency = 0x011d,
    Equalizer1KHzGain = 0x011e,
    Equalizer2KHzFrequency = 0x012c,
    Equalizer2KHzGain = 0x012d,
    Equalizer4KHzFrequency = 0x0120,
    Equalizer4KHzGain = 0x0121,
    Equalizer8KHzFrequency = 0x0109,
    Equalizer8KHzGain = 0x010a,
    Equalizer16KHzFrequency = 0x012f,
    Equalizer16KHzGain = 0x0130,
    CompressorThreshold = 0x013d,
    CompressorRatio = 0x013c,
    CompressorAttack = 0x013e,
    CompressorRelease = 0x013f,
    CompressorMakeUpGain = 0x0140,
    DeEsser = 0x000b,
    ReverbAmount = 0x0076,
    ReverbDecay = 0x002f,
    ReverbEarlyLevel = 0x0037,
    ReverbTailLevel = 0x0039, // Always sent as 0.
    ReverbPredelay = 0x0030,
    ReverbLowColor = 0x0032,
    ReverbHighColor = 0x0033,
    ReverbHighFactor = 0x0034,
    ReverbDiffuse = 0x0031,
    ReverbModSpeed = 0x0035,
    ReverbModDepth = 0x0036,
    ReverbType = 0x002e,
    EchoAmount = 0x0075,
    EchoFeedback = 0x0028,
    EchoTempo = 0x001f,
    EchoDelayL = 0x0022,
    EchoDelayR = 0x0023,
    EchoFeedbackL = 0x0024,
    EchoFeedbackR = 0x0025,
    EchoXFBLtoR = 0x0026,
    EchoXFBRtoL = 0x0027,
    EchoSource = 0x001e,
    EchoDivL = 0x0020,
    EchoDivR = 0x0021,
    EchoFilterStyle = 0x002a,
    PitchAmount = 0x005d,
    PitchCharacter = 0x0167,
    PitchThreshold = 0x0159,
    GenderAmount = 0x0060,
    MegaphoneAmount = 0x003c,
    MegaphonePostGain = 0x0040,
    MegaphoneStyle = 0x003a,
    MegaphoneHP = 0x003d,
    MegaphoneLP = 0x003e,
    MegaphonePreGain = 0x003f,
    MegaphoneDistType = 0x0041,
    MegaphonePresenceGain = 0x0042,
    MegaphonePresenceFC = 0x0043,
    MegaphonePresenceBW = 0x0044,
    MegaphoneBeatboxEnable = 0x0045,
    MegaphoneFilterControl = 0x0046,
    MegaphoneFilter = 0x0047,
    MegaphoneDrivePotGainCompMid = 0x0048,
    MegaphoneDrivePotGainCompMax = 0x0049,
    RobotLowGain = 0x0134,
    RobotLowFreq = 0x0133,
    RobotLowWidth = 0x0135,
    RobotMidGain = 0x013a,
    RobotMidFreq = 0x0139,
    RobotMidWidth = 0x013b,
    RobotHiGain = 0x0137,
    RobotHiFreq = 0x0136,
    RobotHiWidth = 0x0138,
    RobotWaveform = 0x0147,
    RobotPulseWidth = 0x0146,
    RobotThreshold = 0x0157,
    RobotDryMix = 0x014d,
    RobotStyle = 0x0000,
    HardTuneKeySource = 0x0059, // Always sent as 0.
    HardTuneAmount = 0x005a,
    HardTuneRate = 0x005c,
    HardTuneWindow = 0x005b,
    HardTuneScale = 0x005e,
    HardTunePitchAmount = 0x005f,

    RobotEnabled = 0x014e,
    MegaphoneEnabled = 0x00d7,
    HardTuneEnabled = 0x00d8,

    Encoder1Enabled = 0x00d5,
    Encoder2Enabled = 0x00d6,
    Encoder3Enabled = 0x0150,
    Encoder4Enabled = 0x0151,
}

impl From<EffectKeys> for DeviceMicEffectKeys {
    fn from(value: goxlr_shared::microphone::MicEffectKeys) -> Self {
        match value {
            EffectKeys::MicInputMute => DeviceMicEffectKeys::MicInputMute,
            EffectKeys::BleepLevel => DeviceMicEffectKeys::BleepLevel,
            EffectKeys::GateMode => DeviceMicEffectKeys::GateMode,
            EffectKeys::GateThreshold => DeviceMicEffectKeys::GateThreshold,
            EffectKeys::GateEnabled => DeviceMicEffectKeys::GateEnabled,
            EffectKeys::GateAttenuation => DeviceMicEffectKeys::GateAttenuation,
            EffectKeys::GateAttack => DeviceMicEffectKeys::GateAttack,
            EffectKeys::GateRelease => DeviceMicEffectKeys::GateRelease,
            EffectKeys::MicCompSelect => DeviceMicEffectKeys::MicCompSelect,
            EffectKeys::Equalizer31HzFrequency => DeviceMicEffectKeys::Equalizer31HzFrequency,
            EffectKeys::Equalizer31HzGain => DeviceMicEffectKeys::Equalizer31HzGain,
            EffectKeys::Equalizer63HzFrequency => DeviceMicEffectKeys::Equalizer63HzFrequency,
            EffectKeys::Equalizer63HzGain => DeviceMicEffectKeys::Equalizer63HzGain,
            EffectKeys::Equalizer125HzFrequency => DeviceMicEffectKeys::Equalizer125HzFrequency,
            EffectKeys::Equalizer125HzGain => DeviceMicEffectKeys::Equalizer125HzGain,
            EffectKeys::Equalizer250HzFrequency => DeviceMicEffectKeys::Equalizer250HzFrequency,
            EffectKeys::Equalizer250HzGain => DeviceMicEffectKeys::Equalizer250HzGain,
            EffectKeys::Equalizer500HzFrequency => DeviceMicEffectKeys::Equalizer500HzFrequency,
            EffectKeys::Equalizer500HzGain => DeviceMicEffectKeys::Equalizer500HzGain,
            EffectKeys::Equalizer1KHzFrequency => DeviceMicEffectKeys::Equalizer1KHzFrequency,
            EffectKeys::Equalizer1KHzGain => DeviceMicEffectKeys::Equalizer1KHzGain,
            EffectKeys::Equalizer2KHzFrequency => DeviceMicEffectKeys::Equalizer2KHzFrequency,
            EffectKeys::Equalizer2KHzGain => DeviceMicEffectKeys::Equalizer2KHzGain,
            EffectKeys::Equalizer4KHzFrequency => DeviceMicEffectKeys::Equalizer4KHzFrequency,
            EffectKeys::Equalizer4KHzGain => DeviceMicEffectKeys::Equalizer4KHzGain,
            EffectKeys::Equalizer8KHzFrequency => DeviceMicEffectKeys::Equalizer8KHzFrequency,
            EffectKeys::Equalizer8KHzGain => DeviceMicEffectKeys::Equalizer8KHzGain,
            EffectKeys::Equalizer16KHzFrequency => DeviceMicEffectKeys::Equalizer16KHzFrequency,
            EffectKeys::Equalizer16KHzGain => DeviceMicEffectKeys::Equalizer16KHzGain,
            EffectKeys::CompressorThreshold => DeviceMicEffectKeys::CompressorThreshold,
            EffectKeys::CompressorRatio => DeviceMicEffectKeys::CompressorRatio,
            EffectKeys::CompressorAttack => DeviceMicEffectKeys::CompressorAttack,
            EffectKeys::CompressorRelease => DeviceMicEffectKeys::CompressorRelease,
            EffectKeys::CompressorMakeUpGain => DeviceMicEffectKeys::CompressorMakeUpGain,
            EffectKeys::DeEsser => DeviceMicEffectKeys::DeEsser,
            EffectKeys::ReverbAmount => DeviceMicEffectKeys::ReverbAmount,
            EffectKeys::ReverbDecay => DeviceMicEffectKeys::ReverbDecay,
            EffectKeys::ReverbEarlyLevel => DeviceMicEffectKeys::ReverbEarlyLevel,
            EffectKeys::ReverbTailLevel => DeviceMicEffectKeys::ReverbTailLevel,
            EffectKeys::ReverbPredelay => DeviceMicEffectKeys::ReverbPredelay,
            EffectKeys::ReverbLowColor => DeviceMicEffectKeys::ReverbLowColor,
            EffectKeys::ReverbHighColor => DeviceMicEffectKeys::ReverbHighColor,
            EffectKeys::ReverbHighFactor => DeviceMicEffectKeys::ReverbHighFactor,
            EffectKeys::ReverbDiffuse => DeviceMicEffectKeys::ReverbDiffuse,
            EffectKeys::ReverbModSpeed => DeviceMicEffectKeys::ReverbModSpeed,
            EffectKeys::ReverbModDepth => DeviceMicEffectKeys::ReverbModDepth,
            EffectKeys::ReverbType => DeviceMicEffectKeys::ReverbType,
            EffectKeys::EchoAmount => DeviceMicEffectKeys::EchoAmount,
            EffectKeys::EchoFeedback => DeviceMicEffectKeys::EchoFeedback,
            EffectKeys::EchoTempo => DeviceMicEffectKeys::EchoTempo,
            EffectKeys::EchoDelayL => DeviceMicEffectKeys::EchoDelayL,
            EffectKeys::EchoDelayR => DeviceMicEffectKeys::EchoDelayR,
            EffectKeys::EchoFeedbackL => DeviceMicEffectKeys::EchoFeedbackL,
            EffectKeys::EchoFeedbackR => DeviceMicEffectKeys::EchoFeedbackR,
            EffectKeys::EchoXFBLtoR => DeviceMicEffectKeys::EchoXFBLtoR,
            EffectKeys::EchoXFBRtoL => DeviceMicEffectKeys::EchoXFBRtoL,
            EffectKeys::EchoSource => DeviceMicEffectKeys::EchoSource,
            EffectKeys::EchoDivL => DeviceMicEffectKeys::EchoDivL,
            EffectKeys::EchoDivR => DeviceMicEffectKeys::EchoDivR,
            EffectKeys::EchoFilterStyle => DeviceMicEffectKeys::EchoFilterStyle,
            EffectKeys::PitchAmount => DeviceMicEffectKeys::PitchAmount,
            EffectKeys::PitchCharacter => DeviceMicEffectKeys::PitchCharacter,
            EffectKeys::PitchThreshold => DeviceMicEffectKeys::PitchThreshold,
            EffectKeys::GenderAmount => DeviceMicEffectKeys::GenderAmount,
            EffectKeys::MegaphoneAmount => DeviceMicEffectKeys::MegaphoneAmount,
            EffectKeys::MegaphonePostGain => DeviceMicEffectKeys::MegaphonePostGain,
            EffectKeys::MegaphoneStyle => DeviceMicEffectKeys::MegaphoneStyle,
            EffectKeys::MegaphoneHP => DeviceMicEffectKeys::MegaphoneHP,
            EffectKeys::MegaphoneLP => DeviceMicEffectKeys::MegaphoneLP,
            EffectKeys::MegaphonePreGain => DeviceMicEffectKeys::MegaphonePreGain,
            EffectKeys::MegaphoneDistType => DeviceMicEffectKeys::MegaphoneDistType,
            EffectKeys::MegaphonePresenceGain => DeviceMicEffectKeys::MegaphonePresenceGain,
            EffectKeys::MegaphonePresenceFC => DeviceMicEffectKeys::MegaphonePresenceFC,
            EffectKeys::MegaphonePresenceBW => DeviceMicEffectKeys::MegaphonePresenceBW,
            EffectKeys::MegaphoneBeatboxEnable => DeviceMicEffectKeys::MegaphoneBeatboxEnable,
            EffectKeys::MegaphoneFilterControl => DeviceMicEffectKeys::MegaphoneFilterControl,
            EffectKeys::MegaphoneFilter => DeviceMicEffectKeys::MegaphoneFilter,
            EffectKeys::MegaphoneDrivePotGainCompMid => {
                DeviceMicEffectKeys::MegaphoneDrivePotGainCompMid
            }
            EffectKeys::MegaphoneDrivePotGainCompMax => {
                DeviceMicEffectKeys::MegaphoneDrivePotGainCompMax
            }
            EffectKeys::RobotLowGain => DeviceMicEffectKeys::RobotLowGain,
            EffectKeys::RobotLowFreq => DeviceMicEffectKeys::RobotLowFreq,
            EffectKeys::RobotLowWidth => DeviceMicEffectKeys::RobotLowWidth,
            EffectKeys::RobotMidGain => DeviceMicEffectKeys::RobotMidGain,
            EffectKeys::RobotMidFreq => DeviceMicEffectKeys::RobotMidFreq,
            EffectKeys::RobotMidWidth => DeviceMicEffectKeys::RobotMidWidth,
            EffectKeys::RobotHiGain => DeviceMicEffectKeys::RobotHiGain,
            EffectKeys::RobotHiFreq => DeviceMicEffectKeys::RobotHiFreq,
            EffectKeys::RobotHiWidth => DeviceMicEffectKeys::RobotHiWidth,
            EffectKeys::RobotWaveform => DeviceMicEffectKeys::RobotWaveform,
            EffectKeys::RobotPulseWidth => DeviceMicEffectKeys::RobotPulseWidth,
            EffectKeys::RobotThreshold => DeviceMicEffectKeys::RobotThreshold,
            EffectKeys::RobotDryMix => DeviceMicEffectKeys::RobotDryMix,
            EffectKeys::RobotStyle => DeviceMicEffectKeys::RobotStyle,
            EffectKeys::HardTuneKeySource => DeviceMicEffectKeys::HardTuneKeySource,
            EffectKeys::HardTuneAmount => DeviceMicEffectKeys::HardTuneAmount,
            EffectKeys::HardTuneRate => DeviceMicEffectKeys::HardTuneRate,
            EffectKeys::HardTuneWindow => DeviceMicEffectKeys::HardTuneWindow,
            EffectKeys::HardTuneScale => DeviceMicEffectKeys::HardTuneScale,
            EffectKeys::HardTunePitchAmount => DeviceMicEffectKeys::HardTunePitchAmount,
            EffectKeys::RobotEnabled => DeviceMicEffectKeys::RobotEnabled,
            EffectKeys::MegaphoneEnabled => DeviceMicEffectKeys::MegaphoneEnabled,
            EffectKeys::HardTuneEnabled => DeviceMicEffectKeys::HardTuneEnabled,
            EffectKeys::Encoder1Enabled => DeviceMicEffectKeys::Encoder1Enabled,
            EffectKeys::Encoder2Enabled => DeviceMicEffectKeys::Encoder2Enabled,
            EffectKeys::Encoder3Enabled => DeviceMicEffectKeys::Encoder3Enabled,
            EffectKeys::Encoder4Enabled => DeviceMicEffectKeys::Encoder4Enabled,
        }
    }
}

impl From<ParamKeys> for DeviceMicParamKeys {
    fn from(value: ParamKeys) -> Self {
        match value {
            ParamKeys::GateThreshold => DeviceMicParamKeys::GateThreshold,
            ParamKeys::GateAttack => DeviceMicParamKeys::GateAttack,
            ParamKeys::GateRelease => DeviceMicParamKeys::GateRelease,
            ParamKeys::GateAttenuation => DeviceMicParamKeys::GateAttenuation,
            ParamKeys::CompressorThreshold => DeviceMicParamKeys::CompressorThreshold,
            ParamKeys::CompressorRatio => DeviceMicParamKeys::CompressorRatio,
            ParamKeys::CompressorAttack => DeviceMicParamKeys::CompressorAttack,
            ParamKeys::CompressorRelease => DeviceMicParamKeys::CompressorRelease,
            ParamKeys::CompressorMakeUpGain => DeviceMicParamKeys::CompressorMakeUpGain,
            ParamKeys::BleepLevel => DeviceMicParamKeys::BleepLevel,
            ParamKeys::Equalizer90HzFrequency => DeviceMicParamKeys::Equalizer90HzFrequency,
            ParamKeys::Equalizer90HzGain => DeviceMicParamKeys::Equalizer90HzGain,
            ParamKeys::Equalizer250HzFrequency => DeviceMicParamKeys::Equalizer250HzFrequency,
            ParamKeys::Equalizer250HzGain => DeviceMicParamKeys::Equalizer250HzGain,
            ParamKeys::Equalizer500HzFrequency => DeviceMicParamKeys::Equalizer500HzFrequency,
            ParamKeys::Equalizer500HzGain => DeviceMicParamKeys::Equalizer500HzGain,
            ParamKeys::Equalizer1KHzFrequency => DeviceMicParamKeys::Equalizer1KHzFrequency,
            ParamKeys::Equalizer1KHzGain => DeviceMicParamKeys::Equalizer1KHzGain,
            ParamKeys::Equalizer3KHzFrequency => DeviceMicParamKeys::Equalizer3KHzFrequency,
            ParamKeys::Equalizer3KHzGain => DeviceMicParamKeys::Equalizer3KHzGain,
            ParamKeys::Equalizer8KHzFrequency => DeviceMicParamKeys::Equalizer8KHzFrequency,
            ParamKeys::Equalizer8KHzGain => DeviceMicParamKeys::Equalizer8KHzGain,
        }
    }
}
