/*
 As with everything else, we're going to keep the values to these keys isolated in the USB crate
 and have alternatives for direct access in goxlr-shared, where we don't have to care about
 changes
*/

type EffectKeys = goxlr_shared::microphone::MicEffectKeys;
type ParamKeys = goxlr_shared::microphone::MicParamKeys;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) enum MicParamKeys {
    MicType = 0x000,
    XLRGain = 0x001,
    PhantomGain = 0x002,
    JackGain = 0x003,
    GateThreshold = 0x30200,
    GateAttack = 0x30400,
    GateRelease = 0x30600,
    GateAttenuation = 0x30900,
    CompressorThreshold = 0x60200,
    CompressorRatio = 0x60300,
    CompressorAttack = 0x60400,
    CompressorRelease = 0x60600,
    CompressorMakeUpGain = 0x60700,
    BleepLevel = 0x70100,

    /*
     These are the values for the GoXLR mini, it seems there's a difference in how the two
     are setup, The Mini does EQ via microphone parameters, where as the full does it via effects.
    */
    Equalizer90HzFrequency = 0x40000,
    Equalizer90HzGain = 0x40001,
    Equalizer250HzFrequency = 0x40003,
    Equalizer250HzGain = 0x40004,
    Equalizer500HzFrequency = 0x40006,
    Equalizer500HzGain = 0x40007,
    Equalizer1KHzFrequency = 0x50000,
    Equalizer1KHzGain = 0x50001,
    Equalizer3KHzFrequency = 0x50003,
    Equalizer3KHzGain = 0x50004,
    Equalizer8KHzFrequency = 0x50006,
    Equalizer8KHzGain = 0x50007,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) enum MicEffectKeys {
    MicInputMute = 0x0158,
    BleepLevel = 0x0073,
    GateMode = 0x0010,
    GateThreshold = 0x0011,
    GateEnabled = 0x0014,
    GateAttenuation = 0x0015,
    GateAttack = 0x0016,
    GateRelease = 0x0017,
    MicCompSelect = 0x014b,
    Equalizer31HzFrequency = 0x0126,
    Equalizer31HzGain = 0x0127,
    Equalizer63HzFrequency = 0x00f8,
    Equalizer63HzGain = 0x00f9,
    Equalizer125HzFrequency = 0x0113,
    Equalizer125HzGain = 0x0114,
    Equalizer250HzFrequency = 0x0129,
    Equalizer250HzGain = 0x012a,
    Equalizer500HzFrequency = 0x0116,
    Equalizer500HzGain = 0x0117,
    Equalizer1KHzFrequency = 0x011d,
    Equalizer1KHzGain = 0x011e,
    Equalizer2KHzFrequency = 0x012c,
    Equalizer2KHzGain = 0x012d,
    Equalizer4KHzFrequency = 0x0120,
    Equalizer4KHzGain = 0x0121,
    Equalizer8KHzFrequency = 0x0109,
    Equalizer8KHzGain = 0x010a,
    Equalizer16KHzFrequency = 0x012f,
    Equalizer16KHzGain = 0x0130,
    CompressorThreshold = 0x013d,
    CompressorRatio = 0x013c,
    CompressorAttack = 0x013e,
    CompressorRelease = 0x013f,
    CompressorMakeUpGain = 0x0140,
    DeEsser = 0x000b,
    ReverbAmount = 0x0076,
    ReverbDecay = 0x002f,
    ReverbEarlyLevel = 0x0037,
    ReverbTailLevel = 0x0039, // Always sent as 0.
    ReverbPredelay = 0x0030,
    ReverbLowColor = 0x0032,
    ReverbHighColor = 0x0033,
    ReverbHighFactor = 0x0034,
    ReverbDiffuse = 0x0031,
    ReverbModSpeed = 0x0035,
    ReverbModDepth = 0x0036,
    ReverbType = 0x002e,
    EchoAmount = 0x0075,
    EchoFeedback = 0x0028,
    EchoTempo = 0x001f,
    EchoDelayL = 0x0022,
    EchoDelayR = 0x0023,
    EchoFeedbackL = 0x0024,
    EchoFeedbackR = 0x0025,
    EchoXFBLtoR = 0x0026,
    EchoXFBRtoL = 0x0027,
    EchoSource = 0x001e,
    EchoDivL = 0x0020,
    EchoDivR = 0x0021,
    EchoFilterStyle = 0x002a,
    PitchAmount = 0x005d,
    PitchCharacter = 0x0167,
    PitchThreshold = 0x0159,
    GenderAmount = 0x0060,
    MegaphoneAmount = 0x003c,
    MegaphonePostGain = 0x0040,
    MegaphoneStyle = 0x003a,
    MegaphoneHP = 0x003d,
    MegaphoneLP = 0x003e,
    MegaphonePreGain = 0x003f,
    MegaphoneDistType = 0x0041,
    MegaphonePresenceGain = 0x0042,
    MegaphonePresenceFC = 0x0043,
    MegaphonePresenceBW = 0x0044,
    MegaphoneBeatboxEnable = 0x0045,
    MegaphoneFilterControl = 0x0046,
    MegaphoneFilter = 0x0047,
    MegaphoneDrivePotGainCompMid = 0x0048,
    MegaphoneDrivePotGainCompMax = 0x0049,
    RobotLowGain = 0x0134,
    RobotLowFreq = 0x0133,
    RobotLowWidth = 0x0135,
    RobotMidGain = 0x013a,
    RobotMidFreq = 0x0139,
    RobotMidWidth = 0x013b,
    RobotHiGain = 0x0137,
    RobotHiFreq = 0x0136,
    RobotHiWidth = 0x0138,
    RobotWaveform = 0x0147,
    RobotPulseWidth = 0x0146,
    RobotThreshold = 0x0157,
    RobotDryMix = 0x014d,
    RobotStyle = 0x0000,
    HardTuneKeySource = 0x0059, // Always sent as 0.
    HardTuneAmount = 0x005a,
    HardTuneRate = 0x005c,
    HardTuneWindow = 0x005b,
    HardTuneScale = 0x005e,
    HardTunePitchAmount = 0x005f,

    RobotEnabled = 0x014e,
    MegaphoneEnabled = 0x00d7,
    HardTuneEnabled = 0x00d8,

    Encoder1Enabled = 0x00d5,
    Encoder2Enabled = 0x00d6,
    Encoder3Enabled = 0x0150,
    Encoder4Enabled = 0x0151,
}

impl From<EffectKeys> for MicEffectKeys {
    fn from(value: goxlr_shared::microphone::MicEffectKeys) -> Self {
        match value {
            EffectKeys::MicInputMute => MicEffectKeys::MicInputMute,
            EffectKeys::BleepLevel => MicEffectKeys::BleepLevel,
            EffectKeys::GateMode => MicEffectKeys::GateMode,
            EffectKeys::GateThreshold => MicEffectKeys::GateThreshold,
            EffectKeys::GateEnabled => MicEffectKeys::GateEnabled,
            EffectKeys::GateAttenuation => MicEffectKeys::GateAttenuation,
            EffectKeys::GateAttack => MicEffectKeys::GateAttack,
            EffectKeys::GateRelease => MicEffectKeys::GateRelease,
            EffectKeys::MicCompSelect => MicEffectKeys::MicCompSelect,
            EffectKeys::Equalizer31HzFrequency => MicEffectKeys::Equalizer31HzFrequency,
            EffectKeys::Equalizer31HzGain => MicEffectKeys::Equalizer31HzGain,
            EffectKeys::Equalizer63HzFrequency => MicEffectKeys::Equalizer63HzFrequency,
            EffectKeys::Equalizer63HzGain => MicEffectKeys::Equalizer63HzGain,
            EffectKeys::Equalizer125HzFrequency => MicEffectKeys::Equalizer125HzFrequency,
            EffectKeys::Equalizer125HzGain => MicEffectKeys::Equalizer125HzGain,
            EffectKeys::Equalizer250HzFrequency => MicEffectKeys::Equalizer250HzFrequency,
            EffectKeys::Equalizer250HzGain => MicEffectKeys::Equalizer250HzGain,
            EffectKeys::Equalizer500HzFrequency => MicEffectKeys::Equalizer500HzFrequency,
            EffectKeys::Equalizer500HzGain => MicEffectKeys::Equalizer500HzGain,
            EffectKeys::Equalizer1KHzFrequency => MicEffectKeys::Equalizer1KHzFrequency,
            EffectKeys::Equalizer1KHzGain => MicEffectKeys::Equalizer1KHzGain,
            EffectKeys::Equalizer2KHzFrequency => MicEffectKeys::Equalizer2KHzFrequency,
            EffectKeys::Equalizer2KHzGain => MicEffectKeys::Equalizer2KHzGain,
            EffectKeys::Equalizer4KHzFrequency => MicEffectKeys::Equalizer4KHzFrequency,
            EffectKeys::Equalizer4KHzGain => MicEffectKeys::Equalizer4KHzGain,
            EffectKeys::Equalizer8KHzFrequency => MicEffectKeys::Equalizer8KHzFrequency,
            EffectKeys::Equalizer8KHzGain => MicEffectKeys::Equalizer8KHzGain,
            EffectKeys::Equalizer16KHzFrequency => MicEffectKeys::Equalizer16KHzFrequency,
            EffectKeys::Equalizer16KHzGain => MicEffectKeys::Equalizer16KHzGain,
            EffectKeys::CompressorThreshold => MicEffectKeys::CompressorThreshold,
            EffectKeys::CompressorRatio => MicEffectKeys::CompressorRatio,
            EffectKeys::CompressorAttack => MicEffectKeys::CompressorAttack,
            EffectKeys::CompressorRelease => MicEffectKeys::CompressorRelease,
            EffectKeys::CompressorMakeUpGain => MicEffectKeys::CompressorMakeUpGain,
            EffectKeys::DeEsser => MicEffectKeys::DeEsser,
            EffectKeys::ReverbAmount => MicEffectKeys::ReverbAmount,
            EffectKeys::ReverbDecay => MicEffectKeys::ReverbDecay,
            EffectKeys::ReverbEarlyLevel => MicEffectKeys::ReverbEarlyLevel,
            EffectKeys::ReverbTailLevel => MicEffectKeys::ReverbTailLevel,
            EffectKeys::ReverbPredelay => MicEffectKeys::ReverbPredelay,
            EffectKeys::ReverbLowColor => MicEffectKeys::ReverbLowColor,
            EffectKeys::ReverbHighColor => MicEffectKeys::ReverbHighColor,
            EffectKeys::ReverbHighFactor => MicEffectKeys::ReverbHighFactor,
            EffectKeys::ReverbDiffuse => MicEffectKeys::ReverbDiffuse,
            EffectKeys::ReverbModSpeed => MicEffectKeys::ReverbModSpeed,
            EffectKeys::ReverbModDepth => MicEffectKeys::ReverbModDepth,
            EffectKeys::ReverbType => MicEffectKeys::ReverbType,
            EffectKeys::EchoAmount => MicEffectKeys::EchoAmount,
            EffectKeys::EchoFeedback => MicEffectKeys::EchoFeedback,
            EffectKeys::EchoTempo => MicEffectKeys::EchoTempo,
            EffectKeys::EchoDelayL => MicEffectKeys::EchoDelayL,
            EffectKeys::EchoDelayR => MicEffectKeys::EchoDelayR,
            EffectKeys::EchoFeedbackL => MicEffectKeys::EchoFeedbackL,
            EffectKeys::EchoFeedbackR => MicEffectKeys::EchoFeedbackR,
            EffectKeys::EchoXFBLtoR => MicEffectKeys::EchoXFBLtoR,
            EffectKeys::EchoXFBRtoL => MicEffectKeys::EchoXFBRtoL,
            EffectKeys::EchoSource => MicEffectKeys::EchoSource,
            EffectKeys::EchoDivL => MicEffectKeys::EchoDivL,
            EffectKeys::EchoDivR => MicEffectKeys::EchoDivR,
            EffectKeys::EchoFilterStyle => MicEffectKeys::EchoFilterStyle,
            EffectKeys::PitchAmount => MicEffectKeys::PitchAmount,
            EffectKeys::PitchCharacter => MicEffectKeys::PitchCharacter,
            EffectKeys::PitchThreshold => MicEffectKeys::PitchThreshold,
            EffectKeys::GenderAmount => MicEffectKeys::GenderAmount,
            EffectKeys::MegaphoneAmount => MicEffectKeys::MegaphoneAmount,
            EffectKeys::MegaphonePostGain => MicEffectKeys::MegaphonePostGain,
            EffectKeys::MegaphoneStyle => MicEffectKeys::MegaphoneStyle,
            EffectKeys::MegaphoneHP => MicEffectKeys::MegaphoneHP,
            EffectKeys::MegaphoneLP => MicEffectKeys::MegaphoneLP,
            EffectKeys::MegaphonePreGain => MicEffectKeys::MegaphonePreGain,
            EffectKeys::MegaphoneDistType => MicEffectKeys::MegaphoneDistType,
            EffectKeys::MegaphonePresenceGain => MicEffectKeys::MegaphonePresenceGain,
            EffectKeys::MegaphonePresenceFC => MicEffectKeys::MegaphonePresenceFC,
            EffectKeys::MegaphonePresenceBW => MicEffectKeys::MegaphonePresenceBW,
            EffectKeys::MegaphoneBeatboxEnable => MicEffectKeys::MegaphoneBeatboxEnable,
            EffectKeys::MegaphoneFilterControl => MicEffectKeys::MegaphoneFilterControl,
            EffectKeys::MegaphoneFilter => MicEffectKeys::MegaphoneFilter,
            EffectKeys::MegaphoneDrivePotGainCompMid => MicEffectKeys::MegaphoneDrivePotGainCompMid,
            EffectKeys::MegaphoneDrivePotGainCompMax => MicEffectKeys::MegaphoneDrivePotGainCompMax,
            EffectKeys::RobotLowGain => MicEffectKeys::RobotLowGain,
            EffectKeys::RobotLowFreq => MicEffectKeys::RobotLowFreq,
            EffectKeys::RobotLowWidth => MicEffectKeys::RobotLowWidth,
            EffectKeys::RobotMidGain => MicEffectKeys::RobotMidGain,
            EffectKeys::RobotMidFreq => MicEffectKeys::RobotMidFreq,
            EffectKeys::RobotMidWidth => MicEffectKeys::RobotMidWidth,
            EffectKeys::RobotHiGain => MicEffectKeys::RobotHiGain,
            EffectKeys::RobotHiFreq => MicEffectKeys::RobotHiFreq,
            EffectKeys::RobotHiWidth => MicEffectKeys::RobotHiWidth,
            EffectKeys::RobotWaveform => MicEffectKeys::RobotWaveform,
            EffectKeys::RobotPulseWidth => MicEffectKeys::RobotPulseWidth,
            EffectKeys::RobotThreshold => MicEffectKeys::RobotThreshold,
            EffectKeys::RobotDryMix => MicEffectKeys::RobotDryMix,
            EffectKeys::RobotStyle => MicEffectKeys::RobotStyle,
            EffectKeys::HardTuneKeySource => MicEffectKeys::HardTuneKeySource,
            EffectKeys::HardTuneAmount => MicEffectKeys::HardTuneAmount,
            EffectKeys::HardTuneRate => MicEffectKeys::HardTuneRate,
            EffectKeys::HardTuneWindow => MicEffectKeys::HardTuneWindow,
            EffectKeys::HardTuneScale => MicEffectKeys::HardTuneScale,
            EffectKeys::HardTunePitchAmount => MicEffectKeys::HardTunePitchAmount,
            EffectKeys::RobotEnabled => MicEffectKeys::RobotEnabled,
            EffectKeys::MegaphoneEnabled => MicEffectKeys::MegaphoneEnabled,
            EffectKeys::HardTuneEnabled => MicEffectKeys::HardTuneEnabled,
            EffectKeys::Encoder1Enabled => MicEffectKeys::Encoder1Enabled,
            EffectKeys::Encoder2Enabled => MicEffectKeys::Encoder2Enabled,
            EffectKeys::Encoder3Enabled => MicEffectKeys::Encoder3Enabled,
            EffectKeys::Encoder4Enabled => MicEffectKeys::Encoder4Enabled,
        }
    }
}

impl From<ParamKeys> for MicParamKeys {
    fn from(value: ParamKeys) -> Self {
        match value {
            ParamKeys::GateThreshold => MicParamKeys::GateThreshold,
            ParamKeys::GateAttack => MicParamKeys::GateAttack,
            ParamKeys::GateRelease => MicParamKeys::GateRelease,
            ParamKeys::GateAttenuation => MicParamKeys::GateAttenuation,
            ParamKeys::CompressorThreshold => MicParamKeys::CompressorThreshold,
            ParamKeys::CompressorRatio => MicParamKeys::CompressorRatio,
            ParamKeys::CompressorAttack => MicParamKeys::CompressorAttack,
            ParamKeys::CompressorRelease => MicParamKeys::CompressorRelease,
            ParamKeys::CompressorMakeUpGain => MicParamKeys::CompressorMakeUpGain,
            ParamKeys::BleepLevel => MicParamKeys::BleepLevel,
            ParamKeys::Equalizer90HzFrequency => MicParamKeys::Equalizer90HzFrequency,
            ParamKeys::Equalizer90HzGain => MicParamKeys::Equalizer90HzGain,
            ParamKeys::Equalizer250HzFrequency => MicParamKeys::Equalizer250HzFrequency,
            ParamKeys::Equalizer250HzGain => MicParamKeys::Equalizer250HzGain,
            ParamKeys::Equalizer500HzFrequency => MicParamKeys::Equalizer500HzFrequency,
            ParamKeys::Equalizer500HzGain => MicParamKeys::Equalizer500HzGain,
            ParamKeys::Equalizer1KHzFrequency => MicParamKeys::Equalizer1KHzFrequency,
            ParamKeys::Equalizer1KHzGain => MicParamKeys::Equalizer1KHzGain,
            ParamKeys::Equalizer3KHzFrequency => MicParamKeys::Equalizer3KHzFrequency,
            ParamKeys::Equalizer3KHzGain => MicParamKeys::Equalizer3KHzGain,
            ParamKeys::Equalizer8KHzFrequency => MicParamKeys::Equalizer8KHzFrequency,
            ParamKeys::Equalizer8KHzGain => MicParamKeys::Equalizer8KHzGain,
        }
    }
}
